site_name: PengiOS Wiki
theme:
  name: dracula
  # custom_dir: dracula
  colorscheme: dracula
  favicon: img/favicon.ico
  repo_url: https://github.com/PengiOS/PengiOS
  repo_name: PengiOS/PengiOS
  #extra_css: /css/style.css
nav:
- Home: index.md
- Get Started:
  - Why Pengi OS: why.md
  - Get Started: getstarted.md
  - Download: https://github.com/PengiOS/PengiOS/releases
- Installation:
  - PengiOS Beginner: beginner-install.md
  - PengiOS Pro: pro-install.md
- Features:
  - Pengi OS Pro: pro.md
  - Pengi OS Beginner: beginner.md
- Configuration: config.md
- Support:
  - Forums: https://github.com/PengiOS/Forums/discussions
  - FAQ: faq.md
  - Troubleshooting: troubleshoot.md
- Join our discord: https://discord.gg/nEYhYFEfpA\
- Changelogs: https://github.com/pengios/pengios
- Policy:
  - Terms of service: tos.md