site_name: PengiOS Wiki
theme:
  name: dracula
  # custom_dir: dracula
  colorscheme: dracula
  favicon: img/favicon.ico
nav:
- Home: index.md
- Get Started:
  - Why Pengi OS: why.md
  - Get Started: getstarted.md
  - Download: download.md
- Installation:
  - PengiOS Beginner: beginner-install.md
  - PengiOS Pro: pro-install.md
- Features: features.md
- PengiOS Pro: pro.md
- Configuration: config.md
- Support:
  - Forums: https://github.com/PengiOS/Forums/discussions
  - FAQ: faq.md
  - Troubleshooting: troubleshoot.md
- Join our discord: https://discord.gg/nEYhYFEfpA\
- Changelogs: github.com/pengios/pengios
- Policy:
  - Terms of service: tos.md
- R:
  - I:
    - C:
      - K:
        - R:
          - O:
            - L:
              - L: rickroll.md