site_name: Pengi OS
site_url: https://pengios.github.io/wiki/
repo_url: https://github.com/PengiOS/wiki/
repo_name: PengiOS Wiki
edit_uri: edit/main/docs/
theme:
  name: dracula
  # custom_dir: dracula
  colorscheme: dracula
  favicon: img/favicon.ico
  # repo_url: https://github.com/PengiOS/PengiOS
  # repo_name: PengiOS/PengiOS
  #extra_css: /css/style.css
nav:
- Home: index.md
- Get Started:
  - Why Pengi OS: why.md
  - Get Started: getstarted.md
  - Download: https://github.com/PengiOS/PengiOS/releases
- Installation:
  - PengiOS Beginner: beginner-install.md
  - PengiOS Pro: pro-install.md
- Features:
  - Pengi OS Pro: pro.md
  - Pengi OS Beginner: beginner.md
- Configuration: config.md
- Support:
  - Forums: https://github.com/PengiOS/Forums/discussions
  - FAQ: faq.md
  - Troubleshooting: troubleshoot.md
- Join our discord: https://discord.gg/nEYhYFEfpA\
- Changelogs: https://github.com/PengiOS/PengiOS/releases
- Policy:
  - Terms of service: tos.md
extra:
  generator: false
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our wiki and whether you awesome penguins 
      find what they're searching for. With your consent, you're helping us to
      make our wiki and our operating system better.
  homepage: https://pengios.github.io/
