name: Deploy MkDocs to website repo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-dracula-theme

      - name: Build the MkDocs site
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./site/
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        
