name: Deploy MkDocs to website repo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | head -n 1)
          echo "COMMIT_MESSAGE=$(echo $COMMIT_MESSAGE | base64)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-dracula-theme

      - name: Build the MkDocs site
        run: mkdocs build

      - name: Create target directory if it doesn't exist
        run: mkdir -p website-repo/wiki

      - name: Copy the built site
        run: |
          rm -rf website-repo/wiki/*
          cp -r site/* website-repo/wiki/

       - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: releases/v4
          folder: .
          clean: false
          single-commit: true